baseURL = 'https://ejacky.github.io'
languageCode = 'en-us'
title = '反求诸己'
theme = "blank"
summaryLength = 10
timeZone = 'Asia/Shanghai'
[frontmatter]
  lastmod = [":fileModTime", "lastmod"]

[params]
  # Site author
  author = "作者名"

  # homepage 页描述信息
  description = "我的博客站点"
[params.social]
  # Optional, used for attribution in Twitter cards (ideally not a person
  # for example: nytimes, flickr, NatGeo, etc).
  # See: https://dev.twitter.com/cards/types/summary-large-image
  twitter = "username"